import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useSession } from "next-auth/react";
import Link from "next/link";
import MobileNavBar from "../components/mobilenavbar";
import WorkSessions from "../components/worksessions";

const Home: NextPage = () => {
	const { data: session } = useSession();

	return (
		<div className="text-white">
			<Head>
				<title>Work time tracker</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="">
				<nav className="py-2 px-3 shadow-lg">{<MobileNavBar />}</nav>
				<div className="container px-3">
					{session ? <WorkSessions /> : <div>Free work time tracker</div>}
				</div>
			</main>
		</div>
	);
};

export default Home;
